const TOKEN_KEY = 'playerarc.token';

/**
 * When the app is built for a static host (GitHub Pages) there is no server to
 * call, so requests are answered in the browser instead. Everything above this
 * line in the app is identical either way — pages never know which mode they
 * are in.
 */
export const DEMO_MODE = import.meta.env.VITE_DEMO_MODE === 'true';

let demo = null;
async function demoModule() {
  if (!demo) demo = await import('../demo/api.js');
  return demo;
}

export function getToken() {
  return window.localStorage.getItem(TOKEN_KEY);
}
export function setToken(token) {
  if (token) window.localStorage.setItem(TOKEN_KEY, token);
  else window.localStorage.removeItem(TOKEN_KEY);
}

export class ApiError extends Error {
  constructor(message, status, details) {
    super(message);
    this.status = status;
    this.details = details;
  }
}

async function request(path, { method = 'GET', body, isForm = false } = {}) {
  if (DEMO_MODE) {
    const { demoRequest } = await demoModule();
    try {
      return await demoRequest(method, path, isForm ? {} : body);
    } catch (err) {
      if (err.status === 401 && !path.startsWith('/auth/login')) {
        setToken(null);
        window.location.hash = '#/login';
      }
      throw new ApiError(err.message, err.status || 500, err.details);
    }
  }

  const headers = {};
  const token = getToken();
  if (token) headers.Authorization = `Bearer ${token}`;
  if (body && !isForm) headers['Content-Type'] = 'application/json';

  const res = await fetch(`/api${path}`, {
    method,
    headers,
    body: body ? (isForm ? body : JSON.stringify(body)) : undefined,
  });

  if (res.status === 401 && !path.startsWith('/auth/login')) {
    setToken(null);
    window.location.href = '/login';
    throw new ApiError('Your session has ended. Sign in again.', 401);
  }

  const type = res.headers.get('content-type') || '';
  if (!type.includes('application/json')) {
    if (!res.ok) throw new ApiError('The server could not complete that request.', res.status);
    return res;
  }

  const data = await res.json();
  if (!res.ok) throw new ApiError(data.error || 'Something went wrong.', res.status, data.details);
  return data;
}

function saveBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export const api = {
  get: (path) => request(path),
  post: (path, body) => request(path, { method: 'POST', body }),
  put: (path, body) => request(path, { method: 'PUT', body }),
  del: (path) => request(path, { method: 'DELETE' }),
  upload: (path, formData) => request(path, { method: 'POST', body: formData, isForm: true }),

  async download(path, filename) {
    if (DEMO_MODE) {
      // Excel and PDF are generated by the server. The browser demo can still
      // produce CSV, so say plainly what is and is not available here.
      if (!path.endsWith('.csv')) {
        window.alert(
          'Excel and PDF reports are generated on the server, so they are not available in this browser demo.\n\n'
          + 'The CSV export works here, and all three work when you run PlayerArc locally.',
        );
        return;
      }
      const { demoPlayersCsv } = await demoModule();
      saveBlob(new Blob([demoPlayersCsv()], { type: 'text/csv;charset=utf-8' }), filename);
      return;
    }
    const token = getToken();
    const res = await fetch(`/api${path}`, { headers: { Authorization: `Bearer ${token}` } });
    if (!res.ok) throw new ApiError('That export could not be generated.', res.status);
    saveBlob(await res.blob(), filename);
  },
};
